### ISSUE TITLE
Odd Scroll Bar Appears - Child Income

### ISSUE THREAD

**Issue by RichardDudek** [The-Ambit-Group/school-meals#105]
Odd scroll bar appears after I select a frequency then hit the tab button to move on to the next field.  This is happening on CHILD income.  I do not see the same bug on ADULT income.  But I can’t rule out that it doesn’t happen for adult income.
Not specific to any particular income source, although it doesn’t happen on money earned from a full or part time job (the only one with an hourly option).
 
NOTE from RMD:  Assume Google Chrome for this anomaly

Screenshot attached ...
[New bug 11-24 2250.docx](https://github.com/The-Ambit-Group/school-meals/files/610441/New.bug.11-24.2250.docx)

**Comment by ambit-developer** [comment]
Interesting. Probably has to do with this commit: https://github.com/presidential-innovation-fellows/school-meals/commit/7d76ccbed82ce1fc4cb3c9d318f1286de5d72a16

I'm not sure why he wrote that code. Looking into it.

**Comment by ambit-developer** [comment]
@RichardDudek – took a stab at the likely culprit. Please confirm.

**Comment by RichardDudek** [comment]
AD,

Yeah ... Definitely don't need the scroll bar

Lol

I'm still testing ... Looks tight

Regards,

Rick Dudek
Program Manager
The Ambit Group LLC
rdudek@theambitgroup.com<mailto:nbrzostowicz@theambitgroup.com>
(703) 624-0065

On Nov 24, 2016, at 12:43 AM, Ambit Developer <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting. Probably has to do with this commit: presidential-innovation-fellows@7d76ccb<https://github.com/presidential-innovation-fellows/school-meals/commit/7d76ccbed82ce1fc4cb3c9d318f1286de5d72a16>

I'm not sure why he wrote that code. Looking into it.
