### ISSUE TITLE
Missing School District Name in Summary Page Title

### ISSUE THREAD

**Issue by RichardDudek** [The-Ambit-Group/school-meals#107]
1.	Missing “ASD” school district abbreviation in mobile header.  (Is this a mistake, or is this something that Ambit did to reduce the likelihood of wrapping?)

[Bugs 11-25 Missing SD Name Summary Page.docx](https://github.com/The-Ambit-Group/school-meals/files/613686/Bugs.11-25.Missing.SD.Name.Summary.Page.docx)

**Comment by ambit-developer** [comment]
Deliberately removed in c603dd5315f444d6efa49dca814f819801c4ac56 to prevent wrapping in iPhone 5 sized screen widths.

The school district name is immediately visible at the top of the Welcome screen — wrapping is more bad than the short name's presence is good.
