### ISSUE TITLE
Foster Child Mentioned

### ISSUE THREAD

**Issue by RichardDudek** [The-Ambit-Group/school-meals#109]
1.	Shouldn’t mention the foster child.  This is an old issue.  Let’s talk about this one.

not sure what the issue is
[Bugs 11-25 FosterChildError.docx](https://github.com/The-Ambit-Group/school-meals/files/613695/Bugs.11-25.FosterChildError.docx)

**Comment by ambit-developer** [comment]
Got it.

**Comment by RichardDudek** [comment]
Fix verified by RMD - 3:14pm 11/25/2016
