### ISSUE TITLE
Student Foster/H/M/R status only shows if income is provided

### ISSUE THREAD

**Issue by TimOPI** [The-Ambit-Group/school-meals#116]
Student Foster/H/M/R status does not show on summary screen if no income is provided for the student.  This could make it harder for the user to edit from the summary screen, or double check the information they provided and are certifying.

This result comes from:
4 students: 1 foster; 1 homeless; 1 migrant; 1 runaway; income election false
![incomeelectionfalse](https://cloud.githubusercontent.com/assets/22204672/20639018/17354c86-b386-11e6-999f-5487e85f0952.PNG)

If they same case is used but income is given for the students and not adults:
![incomeelectiontrue](https://cloud.githubusercontent.com/assets/22204672/20639037/6c8ac01c-b386-11e6-8264-a3fabb1b27a1.PNG)

**Comment by RichardDudek** [comment]
So the Foster/H/M/R status should be presented on the Summary page for all children?

**Comment by TimOPI** [comment]
@RichardDudek  Yes, please!
