### ISSUE TITLE
Progress Bar to be Disabled after "Submit"

### ISSUE THREAD

**Issue by rcoop017** [The-Ambit-Group/school-meals#123]
⦁	Once the applicant submits the application, the progress bar buttons should be disabled so that the applicant cannot navigate backward, make changes, and submit a second time.   It doesn’t matter whether the progress bar buttons change their appearance when they’re deactivated.  The goal is just to prevent any backward navigation after submission.

![image](https://cloud.githubusercontent.com/assets/22942301/20649354/10a9ccf0-b48c-11e6-8e4f-5d9be491b739.png)

**Comment by ambit-developer** [comment]
Resolved by #2e43c45
