### ISSUE TITLE
Double Question Mark on Salary & Wages Qustion

### ISSUE THREAD

**Issue by rcoop017** [The-Ambit-Group/school-meals#125]
⦁	Double question mark on the salary and wages question on the initial adult income screen (in Spanish only).  [This is a VERY MINOR problem.  Is the extra question mark where the English string is localized?]

![image](https://cloud.githubusercontent.com/assets/22942301/20649365/5c934858-b48c-11e6-831a-36b164d9e275.png)

**Comment by TimOPI** [comment]
@rcoop017 I have this changing waiting for post 4PM call.

**Comment by TimOPI** [comment]
355d673

**Comment by RichardDudek** [comment]
Ambit Dev Team - As Rebecca stated, please hold on this one until after the Launch Logistics & Status call today at 4:00
