### ISSUE TITLE
Icons don't work in IE11

### ISSUE THREAD

**Issue by ambit-developer** [The-Ambit-Group/school-meals#29]
> Icons in status bar, check marks in completed status bar items, and question marks next to underlined tool tip terms do not display in IE11 on FNS laptop running through FNS system. (See screen shot below.)

<img width="1085" alt="screen shot 2016-11-08 at 8 20 11 am" src="https://cloud.githubusercontent.com/assets/23132316/20100594/372ffae8-a58c-11e6-90e7-1a32eca6295b.png">

**Comment by rcoop017** [comment]
This issue stems from possible FNS Laptop restrictions. Rick will talk with NSLP shareholders and inform them that it is not a code-related issue.

**Comment by ambit-developer** [comment]
Unable to reproduce using Browserstack in:

- Windows 7 (IE 11)
- Windows 8.1 (IE 11)
- Windows 8.1 (IE 11 Metro)
- Windows 10 (IE 11)

**Comment by rcoop017** [comment]
@ambit-developer this is an FNS laptop issue, not related to browsers and can be closed.
