### ISSUE TITLE
Help bullets

### ISSUE THREAD

**Issue by ambit-developer** [The-Ambit-Group/school-meals#33]
FNS laptop Chrome 11/03/16

> Strange bulleted spacing on itemized list of reportable income items in HELP

<img width="1079" alt="screen shot 2016-11-08 at 8 28 00 am" src="https://cloud.githubusercontent.com/assets/23132316/20100868/51d52b06-a58d-11e6-918f-1f8657412016.png">

**Comment by TimOPI** [comment]
During localization of the help topic shown in the image, I noticed the following misplaced list item tags:

```
<li>College financial aid for room and board (living expenses), not  including Pell Grants, Supplemental Education Opportunity Grants, State **</li>**Student Incentive Grants, National Direct Student Loans, PLUS, College Work Study, or Byrd Honor Scholarship Programs
<li>Regular cash payments from outside the household (for example, money regularly received from extended family or friends that do not live in **</li>**the household)
```

ffe8601 may have resolved a portion of this issue, as that change removed those misplaced tags.

**Comment by ambit-developer** [comment]
Looks good now:

<img width="917" alt="screen shot 2016-11-16 at 4 18 33 am" src="https://cloud.githubusercontent.com/assets/23132316/20341339/d412dc2c-abb3-11e6-8056-ab983b71315f.png">

Closing.
