### ISSUE TITLE
Enhance summary screen

### ISSUE THREAD

**Issue by ambit-developer** [The-Ambit-Group/school-meals#40]
> (not new instructions, just highlighting / clarifying what is already on the Summary screen mockup, “Summary screen mock-up - income applicant 10-21- 16.docx”) 
>
> Per our last phone call, after the [+ add another source] buttons are added, that data can be displayed on the summary screen as depicted on the original mock-up summary screen by just adding sequential numbers after the name of the source (e.g. salary/wages 1, salary/wages 2, etc.). For each of the income sources, please be sure to use the income source itself as the label, not the income category (e.g. the summary screen should display ‘alimony’ and ‘child support’, not ‘spousal income 1’, ‘spousal income 2’). Use the definitions as shown in the Help topics as source labels. Let us know if you have questions.

-----

**[Household income applicant](https://github.com/The-Ambit-Group/school-meals/files/578294/Summary.screen.mock-up.-.income.applicant.10-21-16.docx)**

![screen shot 2016-11-08 at 8 48 15 am](https://cloud.githubusercontent.com/assets/23132316/20101497/391672de-a590-11e6-97d1-beeccc105c4f.png)

-----

**[Non-household income](https://github.com/The-Ambit-Group/school-meals/files/578295/Summary.screen.mock-up.-.cat.el.applicant.10-21-16.docx)**

<img width="499" alt="screen shot 2016-11-08 at 8 46 43 am" src="https://cloud.githubusercontent.com/assets/23132316/20101487/327a8654-a590-11e6-9683-d69be5e9569d.png">

**Comment by TimOPI** [comment]
![summary screen mock-up - other source cat el applicant 11-10-16](https://cloud.githubusercontent.com/assets/22204672/20186073/80f968b0-a73c-11e6-84f1-0b41e4a1ee5b.png)

**Comment by TimOPI** [comment]
@ambit-developer Thanks for the note regarding the use case we had not covered.  Let me know if the above png covers the missing case.
