### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by ambit-developer** [The-Ambit-Group/school-meals#54]
The application needs the final JSON data structure to be downloaded upon completion.

Tasks include:

- Eliminate "Data" navigation item
- Eliminate final screen showing data (after completion)
- Create downloadable JSON file upon completion

The biggest lift here includes thinking through the final data format and how it should be cleaned before downloaded.

E.g.

- If there are no other kids, should the `otherChildren` item exist? Be null? Be empty?
- If the user enters income then goes back to the beginning and indicates that they have SNAP, should all income related fields be blanked out in the downloaded file?
- etc.

There will probably need to be a "cleanse" that happens before the download to handle these and similar questions (basically, to ensure data integrity). A simple translation function could do this, accepting `applicationData` and returning the same, with some of its properties modified as appropriate.

**Comment by TimOPI** [comment]
Can we maintain, but comment out, the code related to the data button?  We'd like to keep this functionality for future development.

**Comment by rcoop017** [comment]
This should be linked to issue #36 that @bryaNgwa is working on.

**Comment by ambit-developer** [comment]
Duplicate of #36
