### ISSUE TITLE
School Year Auto-Update

### ISSUE THREAD

**Issue by ambit-developer** [The-Ambit-Group/school-meals#6]
Prevent school year from auto-advancing on January 1, per @TimOPI.

Looking for guidance on when the school year should advance (e.g. at what point in a calendar year will families no longer be applying for free/reduced school meals for the current school year).

**Comment by RichardDudek** [comment]
As resolved on November 27, 2016, during NSLP IPT call :

Allow School District to control school year  for NSLP applicants within config.js
