### ISSUE TITLE
Localize remaining strings

### ISSUE THREAD

**Issue by ambit-developer** [The-Ambit-Group/school-meals#64]
A handful of English strings haven't been localized (primarily form labels, it looks like).

Details:

[NSLP-Missing-Textual-Elements-20161116.docx](https://github.com/The-Ambit-Group/school-meals/files/597879/NSLP-Missing-Textual-Elements-20161116.docx)

**Comment by rcoop017** [comment]
[Additional items to be localized 11-20-16.docx](https://github.com/The-Ambit-Group/school-meals/files/602291/Additional.items.to.be.localized.11-20-16.docx) shows:
 
1.      the FAQs and definitions that should appear on each screen,
2.      the ones that actually do appear on each screen (there are some that are wrong that have nothing to do with translations), and
3.      the ones that were not included in the empty.json file, so are not currently in the es.json file and therefore do not appear in Spanish.

[HELP content - 10-24-16.docx](https://github.com/The-Ambit-Group/school-meals/files/602292/HELP.content.-.10-24-16.docx)  & [HELP organization chart - 10-24-16.docx](https://github.com/The-Ambit-Group/school-meals/files/602293/HELP.organization.chart.-.10-24-16.docx) are used as FNS's official list of help topics for each screen.

More to come later...

**Comment by RichardDudek** [comment]
[Non Help items to be localized 11-20-16.docx](https://github.com/The-Ambit-Group/school-meals/files/602665/Non.Help.items.to.be.localized.11-20-16.docx)

**Comment by ambit-developer** [comment]
Update:

The only remaining items to localize are:

- Child income prompt after selecting homeless, migrant, or runaway status (`“You have indicated that Susie does participate in a program …”`)
- Summary screen — Income subtypes and frequencies
- "and" / "or" in dynamic lists of entities

These all require a bit of refactoring. All other language should be localized (and almost all translated -- look for empty quotes in `es.json` for the few strings that need translation).

**Comment by RichardDudek** [comment]
Hey Ross,

Whitney mentioned slight revisions on the summary screen as per the mock ups ... I asked Rebecca to upload info Whitney emailed at COB tonight.  She said it was something to do with the labels for the types of income.

Great job crushing through these CRs ... Talk to you tonight on our 10:00 call

Regards,

Rick Dudek
Program Manager
The Ambit Group LLC
rdudek@theambitgroup.com<mailto:nbrzostowicz@theambitgroup.com>
(703) 624-0065

On Nov 21, 2016, at 6:39 PM, Ambit Developer <notifications@github.com<mailto:notifications@github.com>> wrote:


Update:

The only remaining items to localize are:

  *   Child income prompt after selecting homeless, migrant, or runaway status (“You have indicated that Susie does participate in a program …”)
  *   Summary screen — Income subtypes and frequencies
  *   "and" / "or" in dynamic lists of entities

These all require a bit of refactoring. All other language should be localized (and almost all translated -- look for empty quotes in es.json for the few strings that need translation).
