### ISSUE TITLE
Add IEG image to IEG Help Topic

### ISSUE THREAD

**Issue by TimOPI** [The-Ambit-Group/school-meals#66]
(Self assigning)

Working on adding a placeholder image for the IEG table within the IEG Help Topic.

@ambit-developer What's the best way to compress images?  4ad9f03

**Comment by ambit-developer** [comment]
https://kraken.io/web-interface is a good option for quick simple images. It's also good to make sure the resolution is reasonable (not enormous if it's going to be displayed as relatively small).

**Comment by ambit-developer** [comment]
@TimOPI this is done, correct?

**Comment by TimOPI** [comment]
@ambit-developer Just received word from reviewers that it looks good for version 1.0. Good to close.
