### ISSUE TITLE
Conjugation of verbs required in foreign languages

### ISSUE THREAD

**Issue by RichardDudek** [The-Ambit-Group/school-meals#73]
Foreign languages require conjugation of verbs, which is not currently handled within code.  Need to consider extending variable grammar (such as required when there are multiple children vs single child … “are” or “is”) - Only required where there could be a single person or multiple people (children/adults).

**Comment by ambit-developer** [comment]
`react-intl` has pluralization support for this.

Please provide an example or two of language that varies by plurality, and I will provide an example of how to properly localize it (apologies for missing this the first tie around).

**Comment by RichardDudek** [comment]
Ed Harper is documenting pluralization instance anomalies.  That will be uploaded to GitHub Item #73 as soon as received from Ed's team.

**Comment by RichardDudek** [comment]
AD,

Copy that!

Regards,

Richard M. Dudek
Program Manager
703.624.0065
rdudek@theambitgroup.com<mailto:rdudek@theambitgroup.com>

www.theambitgroup.com<http://www.theambitgroup.com/>
facebook.com/TheAmbitGroup<https://www.facebook.com/TheAmbitGroup>
twitter.com/TheAmbitGroup<https://twitter.com/TheAmbitGroup>


[cid:E9961ED9-CD5D-4C6F-BB3D-C674F5E8BCBD]
WE GET THE MISSION OF GOVERNMENT DONE.
Smarter. Faster. And cheaper.

**Comment by RichardDudek** [comment]
Uploaded Word doc demonstrating parts of NSLP application where pluralization needs to be addressed.

[Translations - use of variables issues 11-20-16.docx](https://github.com/The-Ambit-Group/school-meals/files/602238/Translations.-.use.of.variables.issues.11-20-16.docx)

**Comment by RichardDudek** [comment]
Ancillary issue related to this one ... 

Cited by Ed Harper on Nov 20, 2016

1.      How are we going to handle the **# translation of the strings in config.js** (like school district name and assistance program names) that are used as variables throughout the application?

**Comment by ambit-developer** [comment]
> How are we going to handle the # translation of the strings in config.js (like school district name and assistance program names) that are used as variables throughout the application?

My suggestion would be to treat these as non-translatable proper nouns for now. We can revisit in v2 as needed.

**Comment by RichardDudek** [comment]
AD,

Agreed ... :-)

Regards,

Rick Dudek
Program Manager
The Ambit Group LLC
rdudek@theambitgroup.com<mailto:nbrzostowicz@theambitgroup.com>
(703) 624-0065

On Nov 20, 2016, at 11:59 PM, Ambit Developer <notifications@github.com<mailto:notifications@github.com>> wrote:


How are we going to handle the # translation of the strings in config.js (like school district name and assistance program names) that are used as variables throughout the application?

My suggestion would be to treat these as non-translatable proper nouns for now. We can revisit in v2 as needed.

**Comment by RichardDudek** [comment]
Ross,

Excellent!  I’m tracking as you knock down these items.  Please let me know if I can do anything to keep this process moving swiftly.

I’m at another agency this morning and unfortunately have to focus on their stuff … but I’ll clock out soon and start testing myself.

Great job!

Thanks!

Richard M. Dudek
Program Manager
703.624.0065
rdudek@theambitgroup.com<mailto:rdudek@theambitgroup.com>

www.theambitgroup.com<http://www.theambitgroup.com/>
facebook.com/TheAmbitGroup<https://www.facebook.com/TheAmbitGroup>
twitter.com/TheAmbitGroup<https://twitter.com/TheAmbitGroup>


[cid:E9961ED9-CD5D-4C6F-BB3D-C674F5E8BCBD]
WE GET THE MISSION OF GOVERNMENT DONE.
Smarter. Faster. And cheaper.
