### ISSUE TITLE
Changing Language on 

### ISSUE THREAD

**Issue by RichardDudek** [The-Ambit-Group/school-meals#76]
CHANGING LANGUAGE ON McKinney-Vento HAA Screen THEN USING HELP CRASHES PROGRAM

A little more help on the problem I’m having:

The program crashes when I switch languages and open and close Help on this screen.  It may or may not happen on other screens.  I’m running the application from my FNS HP laptop using Chrome.

 
[NSLP Crashes - Lang change using Help on McKinney-Vento HAA Screen.docx](https://github.com/The-Ambit-Group/school-meals/files/602724/NSLP.Crashes.-.Lang.change.using.Help.on.McKinney-Vento.HAA.Screen.docx)

**Comment by RichardDudek** [comment]
Verified issue in Chrome on Sunday afternoon - RMD

**Comment by RichardDudek** [comment]
Message from Ed - Sunday evening 9:03PM EST

I tried to finish up the list of help items that aren't in the empty.json file.  I've been having a hard time with the application for the past hour.  Lots of crashes when changing languages and opening help.  Also the list of help topics is unstable; sometimes the correct items appear and sometimes a different list appears.  I'm using Chrome on a new non-FNS HP laptop.  I'll try again in the morning.

**Comment by ambit-developer** [comment]
@RichardDudek — fixed and live.

**Comment by RichardDudek** [comment]
AD,

Copy that ... Let me know when you have a new stable deployment for testing.

Thanks!

Regards,

Rick Dudek
Program Manager
The Ambit Group LLC
rdudek@theambitgroup.com<mailto:nbrzostowicz@theambitgroup.com>
(703) 624-0065

On Nov 20, 2016, at 11:57 PM, Ambit Developer <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #76<https://github.com/The-Ambit-Group/school-meals/issues/76> via #78<https://github.com/The-Ambit-Group/school-meals/pull/78>.

**Comment by RichardDudek** [comment]
AD,

Copy that !

Thx!

Regards,

Rick Dudek
Program Manager
The Ambit Group LLC
rdudek@theambitgroup.com<mailto:nbrzostowicz@theambitgroup.com>
(703) 624-0065

On Nov 21, 2016, at 12:01 AM, Ambit Developer <notifications@github.com<mailto:notifications@github.com>> wrote:


@RichardDudek<https://github.com/RichardDudek> — fixed and live.
