### ISSUE TITLE
&nbsp; - Touble with Tribbles 

### ISSUE THREAD

**Issue by RichardDudek** [The-Ambit-Group/school-meals#77]
The notation around tooltips in the commented English text strings look a little different today than they did a couple of days ago.  A couple of days ago the “{tooltip}” tag was surrounded on both sides by “&nbsp;”

Now it looks like there’s an extra space around {tooltip}, but if there’s something there it doesn’t display.

What, if anything, do we need to put in front of and behind “{tooltip}” in the Spanish text?

Example (today):

 See Attachment

Same string a couple of days ago:

  See Attachment
[nbsp and ToolTip issue.docx](https://github.com/The-Ambit-Group/school-meals/files/602738/nbsp.and.ToolTip.issue.docx)

My original Spanish translation for this string included “&nbsp;” on each side of “{tooltip}”.  Should I keep the “&nbsp;” or drop them?

**Comment by ambit-developer** [comment]
It depends. `{tooltip}` is just a placeholder for some other text that shows a tooltip when hovered over.

It it makes sense to have a space around that text, then add a space (e.g. `word {tooltip} word`) — if it doesn't make sense, then don't include a space (e.g. `word, {tooltip}, word`).

`&nbsp;` should not be used in translation files — we've seen that it doesn't display properly. Space literals should be used instead when a space is desired.

**Comment by RichardDudek** [comment]
AD,

Thanks!  Forwarding to Ed.

Regards,

Richard M. Dudek
Program Manager
703.624.0065
rdudek@theambitgroup.com<mailto:rdudek@theambitgroup.com>

www.theambitgroup.com<http://www.theambitgroup.com/>
facebook.com/TheAmbitGroup<https://www.facebook.com/TheAmbitGroup>
twitter.com/TheAmbitGroup<https://twitter.com/TheAmbitGroup>


[cid:E9961ED9-CD5D-4C6F-BB3D-C674F5E8BCBD]
WE GET THE MISSION OF GOVERNMENT DONE.
Smarter. Faster. And cheaper.

**Comment by ambit-developer** [comment]
No problem!

Closing — please reopen if confusion continues around this issue.

**Comment by RichardDudek** [comment]
AD,

Copy that!

Thanks!

Regards,

Rick Dudek
Program Manager
The Ambit Group LLC
rdudek@theambitgroup.com<mailto:nbrzostowicz@theambitgroup.com>
(703) 624-0065

On Nov 21, 2016, at 12:02 AM, Ambit Developer <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #77<https://github.com/The-Ambit-Group/school-meals/issues/77>.
