### ISSUE TITLE
Tool Crashes on Military Screen

### ISSUE THREAD

**Issue by rcoop017** [The-Ambit-Group/school-meals#87]
![image](https://cloud.githubusercontent.com/assets/22942301/20503344/1e8124b6-b010-11e6-8615-8ad8260fe06e.png)

Enter one adult and one child, no case number, no foster status, no H/M/R, no child income.
No additional adults.
Select military income radio button.  Select no to all other income types.

Now you’re on the screen shown above.  
Hit help in English.
Close Help.
Switch to Spanish.
Crashes

**Comment by ambit-developer** [comment]
Fixed and live.
