### ISSUE TITLE
Best Browsers?

### ISSUE THREAD

**Issue by rcoop017** [The-Ambit-Group/school-meals#93]
To cover bases, FNS has asked for a list of the "Best Browsers". I know we mostly test in Chrome so that would be one, but anyone else find a browser that's good and works well with everything?

**Comment by ambit-developer** [comment]
That's subjective, to a point. Chrome is certainly the dominant choice on [desktop](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers#/media/File:Browser_usage_share,_2009%E2%80%932016,_StatCounter.svg) and [mobile](https://www.netmarketshare.com/browser-market-share.aspx?qprid=1&qpcustomb=1&qpsp=209&qpnp=6&qptimeframe=M).

I would suggest the latest version of all major browsers.

**Desktop:**

- Google Chrome (latest)
- Mozilla Firefox (latest)
- Safari (latest)
- Microsoft Internet Explorer (11)*

**Mobile:**

- Google Chrome (latest)
- Mobile Safari (latest)
- Android Browser (latest)

-----

*Note that IE 11 is [available](https://en.wikipedia.org/wiki/Internet_Explorer_version_history#Windows) on Windows 10, 8.1, and 7, which means every release of Windows for the last 7 years can run IE 11 (except Windows 8, which has only [2% market share](https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Desktop_and_laptop_computers) at this point). Therefore, I don't see much reason to be concerned with versions of IE older than IE 11.

**Comment by rcoop017** [comment]
This is a perfect answer. Thanks!
