### ISSUE TITLE
Bug: Residual incomes visible after assistance program selected

### ISSUE THREAD

**Issue by rcoop017** [The-Ambit-Group/school-meals#97]
Been playing around in chrome on iPad, and found some things.

1. Most significantly, I think I've found a reliable way to crash the app. If you fill it out with income, any income, and then add a case number from the summary screen, you can crash whenever you return to the summary screen and attempt to edit any other field. (The income stays on the summary screen even after switching to cat el.) I managed to do this attempting to edit child and adult wages, rental income, and even homeless status, and all gave me the blank screen of doom. I will do some further testing to make sure I'm not off my rocker, but I wanted to flag it.

Resolution: If the Case Number for program is selected, all income information should be removed.

Checkout the images and notes below

[FW__Some_bugs_and_issues.zip](https://github.com/The-Ambit-Group/school-meals/files/609475/FW__Some_bugs_and_issues.zip)

**Comment by rcoop017** [comment]
Additional Info: 

a.	Enter any income-based eligible application. 
•	This will include income for at least one family member
•	It may also include non-Applewood student children (“other kids”), with or without income
•	It may also include other adults, with or without income

b.	From summary screen or through the back button, go back and make it a categorically eligible application.
•	Either add a SNAP, TANF, or FDPIR case number, or
•	Make all Applewood students foster kids, or
•	Make all Applewood students homeless, migrant, or runaway and check the “I do not want to provide income” radio button

c.	Proceed to summary screen

d.	BUG: The summary screen (and the output record) contains information that should have been deleted.  FIX: remove the following information from the summary screen  and from the output record:
•	All non-Applewood “other kids”
•	All adults other than the attestor
•	All income amounts for Applewood students and the attestor

e.	Crash (which might go away by addressing “d” above): At present, the items bulleted above are displayed on the summary screen.  That means that they can be edited.  Hitting edit next to the non-Applewood student names, the adult names other than the attestor, or the income amounts for anybody will cause the program to crash.

**Comment by RichardDudek** [comment]
Update on issue #97:
In addition to deleting income amounts after the user goes back and adds a case number, all non-Applewood children and all adults other than the attestor have to be deleted as well.  Clicking on the edit button next to the name of the “other child” in the example below will crash the program.

BUG: The summary screen (and the output record) contains information that should have been deleted.  FIX: remove the following information from the summary screen  and from the output record:
•	All non-Applewood “other kids” [COMPLETED/FIXED]
•	All adults other than the attestor [COMPLETED/FIXED]
**•	All income amounts for Applewood students and the attestor**

Crash (which might go away by addressing the "All income amounts for Applewood students and the attestor" above): At present, the items bulleted above are displayed on the summary screen.  That means that they can be edited.  Hitting edit next to the non-Applewood student names, the adult names other than the attestor, or the income amounts for anybody will cause the program to crash.

**Comment by ambit-developer** [comment]
Rick – can you try with the latest live version and see if it's still crashable? Been shipping a lot over the past hours. 

Please open a new issue for the cleaning up of the output data.

**Comment by RichardDudek** [comment]
AD,

All good … I tried several different ways in Google Chrome (same scenario that was crashing before does not crash now).

New Issue opened #106 – Clean Up Output File

Also, I will test again once the “Edit” icon is available for “Adults” on the Summary Screen.

Regards,

Richard M. Dudek
Program Manager
703.624.0065
rdudek@theambitgroup.com<mailto:rdudek@theambitgroup.com>

www.theambitgroup.com<http://www.theambitgroup.com/>
facebook.com/TheAmbitGroup<https://www.facebook.com/TheAmbitGroup>
twitter.com/TheAmbitGroup<https://twitter.com/TheAmbitGroup>


[cid:E9961ED9-CD5D-4C6F-BB3D-C674F5E8BCBD]
WE GET THE MISSION OF GOVERNMENT DONE.
Smarter. Faster. And cheaper.

**Comment by ambit-developer** [comment]
Great — just pushed. Feel free to take it for a spin.

**Comment by RichardDudek** [comment]
Summary Screen turns out right, and system does not crash anymore.  However, the previously entered incomes still end up on the Output File ... sorry, I don't know if that was ever mentioned in the initial description of the problem.  They basically want all previously entered income information to be wiped out if the person filling out the application selects one of the benefit programs after already entering income information.

**Comment by RichardDudek** [comment]
Output File (income data should be deleted once user clicks Continue button after checking one of the benefit programs):

{
  "students": [
    {
      "id": "rycTfb4Mx",
      "isChild": true,
      "incomeTypes": {
        "child": {
          "isApplicable": true,
          "sources": {
            "job": {
              "has": true,
              "amount": "25",
              "frequency": "weekly",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "socialSecurity": {
              "has": true,
              "amount": "100",
              "frequency": "monthly",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "friendsFamily": {
              "has": true,
              "amount": "200",
              "frequency": "monthly",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "pensionAnnuityTrust": {
              "has": true,
              "amount": "111",
              "frequency": "weekly",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "other": {
              "has": true,
              "amount": "55",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            }
          }
        }
      },
      "isStudent": true,
      "isFoster": false,
      "isHomeless": false,
      "isMigrant": false,
      "isRunaway": false,
      "demographics": {
        "isNativeAmerican": null,
        "isAsian": null,
        "isBlack": null,
        "isPacificIslander": null,
        "isWhite": null,
        "isHispanicLatino": null
      },
      "firstName": "Jenny",
      "middleName": "",
      "lastName": "Smith",
      "suffix": "",
      "school": "VES",
      "grade": "3"
    }
  ],
  "assistancePrograms": {
    "items": [
      {
        "isApplicable": true,
        "id": "SkecpfbEfl",
        "name": "Supplemental Nutrition Assistance Program (SNAP)",
        "accronym": "SNAP",
        "caseNumber": "55588888"
      },
      {
        "isApplicable": null,
        "id": "Hy-96MZVGl",
        "name": "Temporary Assistance for Needy Families (TANF)",
        "accronym": "TANF",
        "caseNumber": ""
      },
      {
        "isApplicable": null,
        "id": "Bkz5pGWVMl",
        "name": "Food Distribution Program on Indian Reservations (FDPIR)",
        "accronym": "FDPIR",
        "caseNumber": ""
      }
    ]
  },
  "otherChildren": [],
  "adults": [
    {
      "id": "B1X9azW4Gl",
      "isAdult": true,
      "isAttestor": true,
      "incomeTypes": {
        "military": {
          "isApplicable": true,
          "isDeployed": true,
          "sources": {
            "basic": {
              "has": true,
              "amount": "123",
              "frequency": "monthly",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "cashBonus": {
              "has": true,
              "amount": "200",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "allowance": {
              "has": true,
              "amount": "50",
              "frequency": "weekly",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            }
          }
        },
        "employment": {
          "isApplicable": false,
          "sources": {
            "salaryWages": {
              "has": true,
              "amount": "111",
              "frequency": "everyTwoWeeks",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "tips": {
              "has": true,
              "amount": "44",
              "frequency": "weekly",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "commission": {
              "has": true,
              "amount": "88",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "cashBonus": {
              "has": true,
              "amount": "66",
              "frequency": "everyTwoWeeks",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "selfEmployment": {
              "has": true,
              "amount": "99",
              "frequency": "everyTwoWeeks",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            }
          }
        },
        "publicAssistance": {
          "isApplicable": true,
          "sources": {
            "ssi": {
              "has": true,
              "amount": "75",
              "frequency": "monthly",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "stateLocal": {
              "has": true,
              "amount": "87",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            }
          }
        },
        "spousal": {
          "isApplicable": true,
          "sources": {
            "alimony": {
              "has": true,
              "amount": "98",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "childSupport": {
              "has": true,
              "amount": "56",
              "frequency": "everyTwoWeeks",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            }
          }
        },
        "unemployment": {
          "isApplicable": true,
          "sources": {
            "unemployment": {
              "has": true,
              "amount": "33",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "workersComp": {
              "has": true,
              "amount": "80000",
              "frequency": "weekly",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "strike": {
              "has": true,
              "amount": "777",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "ssdi": {
              "has": true,
              "amount": "852",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "veteran": {
              "has": true,
              "amount": "987",
              "frequency": "everyTwoWeeks",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            }
          }
        },
        "retirement": {
          "isApplicable": true,
          "sources": {
            "socialSecurity": {
              "has": true,
              "amount": "258",
              "frequency": "monthly",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "privatePension": {
              "has": true,
              "amount": "162",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            }
          }
        },
        "other": {
          "isApplicable": true,
          "sources": {
            "regularCashPayments": {
              "has": true,
              "amount": "85",
              "frequency": "everyTwoWeeks",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "rentalIncome": {
              "has": true,
              "amount": "75",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "earnedInterest": {
              "has": true,
              "amount": "45",
              "frequency": "weekly",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "investmentIncome": {
              "has": true,
              "amount": "12",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "annuity": {
              "has": true,
              "amount": "65",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            },
            "other": {
              "has": true,
              "amount": "55",
              "frequency": "twicePerMonth",
              "hourlyHours": "",
              "hourlyPeriod": "",
              "more": []
            }
          }
        }
      },
      "firstName": "Joe",
      "middleName": "",
      "lastName": "Smith",
      "suffix": ""
    }
  ],
  "certifiedCorrect": true,
  "electToProvideIncome": null,
  "attestation": {
    "date": "11/24/2016"
  },
  "contact": {
    "phone": "",
    "email": "",
    "address1": "",
    "address2": "",
    "city": "",
    "state": "",
    "zip": ""
  },
  "signature": {
    "hasSsn": true,
    "ssnLastFour": "0586"
  }
}


Richard M. Dudek
Program Manager
703.624.0065
rdudek@theambitgroup.com<mailto:rdudek@theambitgroup.com>

www.theambitgroup.com<http://www.theambitgroup.com/>
facebook.com/TheAmbitGroup<https://www.facebook.com/TheAmbitGroup>
twitter.com/TheAmbitGroup<https://twitter.com/TheAmbitGroup>


[cid:E9961ED9-CD5D-4C6F-BB3D-C674F5E8BCBD]
WE GET THE MISSION OF GOVERNMENT DONE.
Smarter. Faster. And cheaper.

**Comment by RichardDudek** [comment]
File Output from Test Run ... entered income for every source possible ... then, at Summary Page, returned to Benefit Program page and selected SNAP ... entered Case # and completed process.
All Income Data and Foster Children should be removed from application data structure (hash) when user selects one of the Benefit Programs.

Output File Attached (changed filetype to .txt to enable upload):

[nslp-data-Thursday3pm.json.txt](https://github.com/The-Ambit-Group/school-meals/files/612110/nslp-data-Thursday3pm.json.txt)

**Comment by RichardDudek** [comment]
BUG: The summary screen (and the output record) contains information that should have been deleted. FIX: remove the following information from the summary screen and from the output record:
• All non-Applewood “other kids” [COMPLETED/FIXED]
• All adults other than the attestor [COMPLETED/FIXED]
• All income amounts for Applewood students and the attestor

**Comment by RichardDudek** [comment]
Closing ... Opened #106 for issue regarding income in Output File
