### ISSUE TITLE
Red Warning Text Doesn't Wrap

### ISSUE THREAD

**Issue by rcoop017** [The-Ambit-Group/school-meals#98]
1.	Red warning text at bottom doesn’t wrap.  Actual Android phone and iPhone 5 emulator in Chrome on FNS laptop.

![image](https://cloud.githubusercontent.com/assets/22942301/20573738/46872878-b17f-11e6-8eaa-596f0e4b125c.png)

**Comment by ambit-developer** [comment]
Also observed on real iPhone.
